import { pageMetadata } from "@/lib/metadata";
import { CTASection } from "@/components/CTASection";
import { EntityCards } from "@/components/EntityCards";
export const metadata = pageMetadata({ title: "Company", description: "Meet Trafexa Nordic AB in Sweden and Diversa Solutions LLC in Wyoming. Digital products, business software and considered engineering.", path: "/about" });
export default function AboutPage() {
  return <><section className="page-hero"><div className="container"><p className="eyebrow">The company</p><h1>We care about<br />how the work works.</h1><p className="page-lead">We develop our own digital products and build software for businesses with a specific operational need. Product thinking and engineering belong in the same conversation.</p></div></section>
    <section className="section"><div className="container two-column"><h2>Useful software starts<br />with a real understanding.</h2><div className="rich-copy"><p>A customer request. A contract. A document waiting for a signature. These are the things a business runs on. Our work is about making the systems around them clearer and more connected.</p><p>Our portfolio spans accounting, energy operations, signing, customer management and planning. Each product addresses a distinct operational need, with its current development stage noted in the portfolio.</p><p>For a new engagement, we begin with the people who will use the product, the information they rely on and the decisions they need to make.</p></div></div></section>
    <section className="section entity-section"><div className="container"><div className="section-heading"><p className="eyebrow">Legal entities</p><h2>Two entities.<br />Clear responsibilities.</h2><p>Trafexa Nordic AB and Diversa Solutions LLC are presented separately. The entity responsible for a project is named in the proposal and contract.</p></div><EntityCards /><p className="entity-note">Enquiries through this website are handled by Trafexa Nordic AB. Mention the US entity in your enquiry when relevant; the appropriate arrangement is confirmed before an engagement begins.</p></div></section><CTASection /></>;
}
