import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";
import { company } from "@/lib/company";
export const metadata:Metadata={title:"Privacy notice",description:"How we handle information when you visit, contact us or submit an application.",alternates:{canonical:"/privacy"}};
export default function PrivacyPage(){return <LegalPage title="Privacy notice" intro="How we handle information when you visit, contact us or submit an application." sections={[
 ["The website operator",`${company.name}, company registration number ${company.orgNumber}, is responsible for the processing described in this notice. Contact ${company.email} with questions. Diversa Solutions LLC is a separate Wyoming entity; a project agreement will identify the relevant contracting entity. Selecting an entity in an enquiry does not itself enter you into an agreement.`],
 ["Information we process","We may process your name, email address, telephone number, company name, registration number, industry, website, project or payment requirements, application status and messages. Technical security and log information may also be processed to operate the website and protect the services."],
 ["Purpose and legal basis","We use information to respond to enquiries, handle applications, administer onboarding, communicate with you, protect the service and meet legal obligations. Depending on the circumstances, processing is based on steps before or performance of a contract, our legitimate interests in business relationships and security, a legal obligation, or consent where appropriate."],
 ["Service providers and recipients","We may use providers for hosting, databases, email, security and other technical functions. Where an application concerns business payments, necessary information may be shared with a relevant payment or financial provider for further onboarding when there is a legal basis and you have received the required information."],
 ["Transfers outside the EU/EEA","Where a provider processes personal data outside the EU/EEA, an appropriate transfer mechanism is required when the GDPR applies. This may include an adequacy decision or the European Commission’s standard contractual clauses, together with additional safeguards where needed."],
 ["Retention","We retain personal data for as long as needed for enquiries, applications, administration, customer relationships, security, legal claims or statutory requirements. It is then deleted or anonymised under the applicable procedures and backup cycles."],
 ["Your rights",`Depending on the circumstances, you may have rights to access, correct or erase your data, restrict or object to processing, and data portability. Where processing relies on consent, you may withdraw that consent. Contact ${company.email} to exercise your rights.`],
 ["Complaints","You may lodge a complaint with the Swedish Authority for Privacy Protection, IMY, if you believe your personal data is being processed contrary to data protection rules."],
 ["Advertising",`${company.name} does not sell personal data to advertisers.`],
 ]}/>;}
